name: Deploy Backend
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Copy docker-compose via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "~/app"
          
      - name: Execute SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            if [ ! -d "notification-system-backend" ]; then
              git clone https://github.com/rufijey/notification-system-backend notification-system-backend
            fi
            cd notification-system-backend
            git pull origin master
            cp ~/app/.env .env
            sudo journalctl --vacuum-size=50M || true
            sudo apt-get clean || true
            sudo docker builder prune -af || true
            sudo docker system prune -af --volumes || true
            sudo docker-compose -f docker-compose.prod.yml up -d --build
